name: Build Package Distribution
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build Distributions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.x"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r build/requirements.txt

      - name: Build Distribution
        run: |
          python -m build

  docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.x"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r docs/requirements.txt

      - name: Build Documentation
        run: |
          cd docs
          make html
